[package]
org = "ballerinax"
name = "activemq.driver"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["ActiveMQ"]
repository = "https://github.com/ballerina-platform/module-ballerinax-activemq.driver"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
path = "./lib/activemq-client-5.18.2.jar"

[[platform.java11.dependency]]
path = "./lib/geronimo-j2ee-management_1.1_spec-1.0.1.jar"

[[platform.java11.dependency]]
path = "./lib/hawtbuf-1.11.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "activemq.driver-native"
version = "0.1.0"
path = "../native/build/libs/activemq.driver-native-0.1.0-SNAPSHOT.jar"
